name: build

on:
  push:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        env:
           VER: '0.99.0'
        run: |
           docker build --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg VERSION=$VER -t navir/opensuseleap-for-flexiblesusy -t navir/opensuseleap-for-flexiblesusy:$VER .
           docker push navir/opensuseleap-for-flexiblesusy:$VER
           # docker push navir/opensuseleap-for-flexiblesusy:latest

