name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build and push
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t navir/opensuseleap-for-flexiblesusy -t navir/opensuseleap-for-flexiblesusy:0.2.0 .
          docker push navir/opensuseleap-for-flexiblesusy:0.2.0
          docker push navir/opensuseleap-for-flexiblesusy
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
