name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker build
        run: docker build -t navir/opensuseleap-for-flexiblesusy -t navir/opensuseleap-for-flexiblesusy:0.2.0 .

      - name: Docker push
        run: |
          docker push navir/opensuseleap-for-flexiblesusy:0.2.0
          docker push navir/opensuseleap-for-flexiblesusy
          
