name: build

on:
  push:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
           VER: '0.17.5'
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: navir/opensuseleap-for-flexiblesusy:latest,navir/opensuseleap-for-flexiblesusy:${{env.VER}}
          build-args: BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ'),VERSION=${{env.VER}}

