on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build and push
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker build -t navir/opensuseleap-for-flexiblesusy -t navir/opensuseleap-for-flexiblesusy:0.2.0 .
          docker push navir/opensuseleap-for-flexiblesusy:0.2.0
          docker push navir/opensuseleap-for-flexiblesusy
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
